apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-api-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: flask-api-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-api-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: flask-api-sa
    namespace: default
roleRef:
  kind: Role
  name: flask-api-role
  apiGroup: rbac.authorization.k8s.io
